package com.rahgozar.app.panel

import com.google.gson.annotations.SerializedName

/**
 * The file baked into the build: the keys to trust, the addresses to try first,
 * and where to look when none of them answer.
 *
 * Generated by the panel (کشف آدرس → دانلود discovery.json) rather than written
 * by hand, so the addresses the app tries cannot drift from the mirrors the
 * panel publishes to. Re-export and re-embed after every mirror change.
 */
data class DiscoveryDocument(
    @SerializedName("key_id") val keyId: String = "",
    @SerializedName("sign_public_key") val signPublicKey: String = "",
    @SerializedName("exch_public_key") val exchPublicKey: String = "",
    @SerializedName("direct_endpoints") val directEndpoints: List<PanelEndpoint> = emptyList(),
    @SerializedName("sources") val sources: List<DiscoverySource> = emptyList(),
    @SerializedName("doh_resolvers") val dohResolvers: List<String> = emptyList(),
    @SerializedName("timeout_ms") val timeoutMs: Int = 4000,
    @SerializedName("generated_at") val generatedAt: Long = 0,
)

data class PanelEndpoint(
    @SerializedName("url") val url: String = "",
    @SerializedName("weight") val weight: Int = 0,
)

data class DiscoverySource(
    /** "http" is fetched and parsed; "doh_txt" needs a DNS query first. */
    @SerializedName("type") val type: String = "",
    @SerializedName("url") val url: String = "",
    @SerializedName("domain") val domain: String = "",
    @SerializedName("name") val name: String = "",
    @SerializedName("priority") val priority: Int = 0,
) {
    val isHttp get() = type == TYPE_HTTP
    val isDohTxt get() = type == TYPE_DOH_TXT

    /** The fully-qualified TXT record name, for doh_txt sources. */
    val txtName get() = "${name.ifEmpty { "_cfg" }}.$domain"

    /** Identity for de-duplicating a merged list. */
    val key get() = if (isDohTxt) "txt:$txtName" else "http:$url"

    companion object {
        const val TYPE_HTTP = "http"
        const val TYPE_DOH_TXT = "doh_txt"
    }
}

/**
 * The signed payload inside a bundle: where the panel answers, plus the mirror
 * list so an install that reaches any one live source learns about all the
 * others — including mirrors added after that build shipped.
 */
data class EndpointBundle(
    @SerializedName("version") val version: Long = 0,
    @SerializedName("endpoints") val endpoints: List<PanelEndpoint> = emptyList(),
    @SerializedName("sources") val sources: List<DiscoverySource> = emptyList(),
    @SerializedName("not_before") val notBefore: Long = 0,
    @SerializedName("not_after") val notAfter: Long = 0,
)
