/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class DnsAddress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DnsAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DnsAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DnsAddress obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_DnsAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DnsAddress() {
    this(ovpncliJNI.new_DnsAddress__SWIG_0(), true);
  }

  public DnsAddress(String address_input) {
    this(ovpncliJNI.new_DnsAddress__SWIG_1(address_input), true);
  }

  public String to_string() {
    return ovpncliJNI.DnsAddress_to_string(swigCPtr, this);
  }

  public void validate(String title) {
    ovpncliJNI.DnsAddress_validate(swigCPtr, this, title);
  }

  public void setAddress(String value) {
    ovpncliJNI.DnsAddress_address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ovpncliJNI.DnsAddress_address_get(swigCPtr, this);
  }

  public void setPort(long value) {
    ovpncliJNI.DnsAddress_port_set(swigCPtr, this, value);
  }

  public long getPort() {
    return ovpncliJNI.DnsAddress_port_get(swigCPtr, this);
  }

}
