/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class DnsDomain {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DnsDomain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DnsDomain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DnsDomain obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_DnsDomain(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DnsDomain() {
    this(ovpncliJNI.new_DnsDomain__SWIG_0(), true);
  }

  public DnsDomain(String domain_) {
    this(ovpncliJNI.new_DnsDomain__SWIG_1(domain_), true);
  }

  public String to_string() {
    return ovpncliJNI.DnsDomain_to_string(swigCPtr, this);
  }

  public void validate(String title) {
    ovpncliJNI.DnsDomain_validate(swigCPtr, this, title);
  }

  public void setDomain(String value) {
    ovpncliJNI.DnsDomain_domain_set(swigCPtr, this, value);
  }

  public String getDomain() {
    return ovpncliJNI.DnsDomain_domain_get(swigCPtr, this);
  }

}
