/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class DnsOptions_DomainsList extends java.util.AbstractList<DnsDomain> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DnsOptions_DomainsList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DnsOptions_DomainsList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DnsOptions_DomainsList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_DnsOptions_DomainsList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public DnsOptions_DomainsList(DnsDomain[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (DnsDomain element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public DnsOptions_DomainsList(Iterable<DnsDomain> initialElements) {
    this();
    for (DnsDomain element : initialElements) {
      doAdd(element);
    }
  }

  public DnsDomain get(int index) {
    return doGet(index);
  }

  public DnsDomain set(int index, DnsDomain e) {
    return doSet(index, e);
  }

  public boolean add(DnsDomain e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, DnsDomain e) {
    modCount++;
    doAdd(index, e);
  }

  public DnsDomain remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public DnsOptions_DomainsList() {
    this(ovpncliJNI.new_DnsOptions_DomainsList__SWIG_0(), true);
  }

  public DnsOptions_DomainsList(DnsOptions_DomainsList other) {
    this(ovpncliJNI.new_DnsOptions_DomainsList__SWIG_1(DnsOptions_DomainsList.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return ovpncliJNI.DnsOptions_DomainsList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ovpncliJNI.DnsOptions_DomainsList_clear(swigCPtr, this);
  }

  public DnsOptions_DomainsList(int count, DnsDomain value) {
    this(ovpncliJNI.new_DnsOptions_DomainsList__SWIG_2(count, DnsDomain.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return ovpncliJNI.DnsOptions_DomainsList_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    ovpncliJNI.DnsOptions_DomainsList_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return ovpncliJNI.DnsOptions_DomainsList_doSize(swigCPtr, this);
  }

  private void doAdd(DnsDomain x) {
    ovpncliJNI.DnsOptions_DomainsList_doAdd__SWIG_0(swigCPtr, this, DnsDomain.getCPtr(x), x);
  }

  private void doAdd(int index, DnsDomain x) {
    ovpncliJNI.DnsOptions_DomainsList_doAdd__SWIG_1(swigCPtr, this, index, DnsDomain.getCPtr(x), x);
  }

  private DnsDomain doRemove(int index) {
    return new DnsDomain(ovpncliJNI.DnsOptions_DomainsList_doRemove(swigCPtr, this, index), true);
  }

  private DnsDomain doGet(int index) {
    return new DnsDomain(ovpncliJNI.DnsOptions_DomainsList_doGet(swigCPtr, this, index), false);
  }

  private DnsDomain doSet(int index, DnsDomain val) {
    return new DnsDomain(ovpncliJNI.DnsOptions_DomainsList_doSet(swigCPtr, this, index, DnsDomain.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    ovpncliJNI.DnsOptions_DomainsList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
