/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class DnsOptions_ServersMap extends java.util.AbstractMap<Integer, DnsServer> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DnsOptions_ServersMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DnsOptions_ServersMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DnsOptions_ServersMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_DnsOptions_ServersMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof Integer)) {
      return false;
    }

    return containsImpl((Integer)key);
  }

  public DnsServer get(java.lang.Object key) {
    if (!(key instanceof Integer)) {
      return null;
    }

    Iterator itr = find((Integer) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public DnsServer put(Integer key, DnsServer value) {
    Iterator itr = find(key);
    if (itr.isNot(end())) {
      DnsServer oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public DnsServer remove(java.lang.Object key) {
    if (!(key instanceof Integer)) {
      return null;
    }

    Iterator itr = find((Integer) key);
    if (itr.isNot(end())) {
      DnsServer oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<Integer, DnsServer>> entrySet() {
    java.util.Set<Entry<Integer, DnsServer>> setToReturn =
        new java.util.HashSet<Entry<Integer, DnsServer>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<Integer, DnsServer>() {
        private Iterator iterator;

        private Entry<Integer, DnsServer> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public Integer getKey() {
          return iterator.getKey();
        }

        public DnsServer getValue() {
          return iterator.getValue();
        }

        public DnsServer setValue(DnsServer newValue) {
          DnsServer oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public DnsOptions_ServersMap() {
    this(ovpncliJNI.new_DnsOptions_ServersMap__SWIG_0(), true);
  }

  public DnsOptions_ServersMap(DnsOptions_ServersMap other) {
    this(ovpncliJNI.new_DnsOptions_ServersMap__SWIG_1(DnsOptions_ServersMap.getCPtr(other), other), true);
  }

  static public class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ovpncliJNI.delete_DnsOptions_ServersMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private DnsOptions_ServersMap.Iterator getNextUnchecked() {
      return new DnsOptions_ServersMap.Iterator(ovpncliJNI.DnsOptions_ServersMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(DnsOptions_ServersMap.Iterator other) {
      return ovpncliJNI.DnsOptions_ServersMap_Iterator_isNot(swigCPtr, this, DnsOptions_ServersMap.Iterator.getCPtr(other), other);
    }
  
    private int getKey() {
      return ovpncliJNI.DnsOptions_ServersMap_Iterator_getKey(swigCPtr, this);
    }
  
    private DnsServer getValue() {
      return new DnsServer(ovpncliJNI.DnsOptions_ServersMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(DnsServer newValue) {
      ovpncliJNI.DnsOptions_ServersMap_Iterator_setValue(swigCPtr, this, DnsServer.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return ovpncliJNI.DnsOptions_ServersMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ovpncliJNI.DnsOptions_ServersMap_clear(swigCPtr, this);
  }

  private DnsOptions_ServersMap.Iterator find(int key) {
    return new DnsOptions_ServersMap.Iterator(ovpncliJNI.DnsOptions_ServersMap_find(swigCPtr, this, key), true);
  }

  private DnsOptions_ServersMap.Iterator begin() {
    return new DnsOptions_ServersMap.Iterator(ovpncliJNI.DnsOptions_ServersMap_begin(swigCPtr, this), true);
  }

  private DnsOptions_ServersMap.Iterator end() {
    return new DnsOptions_ServersMap.Iterator(ovpncliJNI.DnsOptions_ServersMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return ovpncliJNI.DnsOptions_ServersMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(int key) {
    return ovpncliJNI.DnsOptions_ServersMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(int key, DnsServer value) {
    ovpncliJNI.DnsOptions_ServersMap_putUnchecked(swigCPtr, this, key, DnsServer.getCPtr(value), value);
  }

  private void removeUnchecked(DnsOptions_ServersMap.Iterator itr) {
    ovpncliJNI.DnsOptions_ServersMap_removeUnchecked(swigCPtr, this, DnsOptions_ServersMap.Iterator.getCPtr(itr), itr);
  }

}
