/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public class DnsOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DnsOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DnsOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(DnsOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ovpncliJNI.delete_DnsOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DnsOptions() {
    this(ovpncliJNI.new_DnsOptions(), true);
  }

  public String to_string() {
    return ovpncliJNI.DnsOptions_to_string(swigCPtr, this);
  }

  public void setFrom_dhcp_options(boolean value) {
    ovpncliJNI.DnsOptions_from_dhcp_options_set(swigCPtr, this, value);
  }

  public boolean getFrom_dhcp_options() {
    return ovpncliJNI.DnsOptions_from_dhcp_options_get(swigCPtr, this);
  }

  public void setSearch_domains(DnsOptions_DomainsList value) {
    ovpncliJNI.DnsOptions_search_domains_set(swigCPtr, this, DnsOptions_DomainsList.getCPtr(value), value);
  }

  public DnsOptions_DomainsList getSearch_domains() {
    long cPtr = ovpncliJNI.DnsOptions_search_domains_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DnsOptions_DomainsList(cPtr, false);
  }

  public void setServers(DnsOptions_ServersMap value) {
    ovpncliJNI.DnsOptions_servers_set(swigCPtr, this, DnsOptions_ServersMap.getCPtr(value), value);
  }

  public DnsOptions_ServersMap getServers() {
    long cPtr = ovpncliJNI.DnsOptions_servers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DnsOptions_ServersMap(cPtr, false);
  }

}
