/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.openvpn.ovpn3;

public interface LogReceiverSwigInterface {
  long LogReceiverSwigInterface_GetInterfaceCPtr();
  void log(ClientAPI_LogInfo arg0);
}
