package com.rahgozar.app.panel

import com.google.gson.Gson
import com.google.gson.annotations.SerializedName
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Holds this implementation to the panel's, byte for byte.
 *
 * The vectors are generated by the production Go code (`go run
 * ./cmd/testvectors`) and read straight out of the panel's testdata directory —
 * see the test resources srcDir in build.gradle.kts. Two implementations of the
 * same spec agreeing is the only evidence that matters here; a test written
 * against this file's own reading of docs/CRYPTO.md would pass whatever it
 * happened to do.
 */
class PanelCryptoTest {

    private data class Server(
        @SerializedName("sign_public_key") val signPublicKey: String,
        @SerializedName("exch_public_key") val exchPublicKey: String,
        @SerializedName("key_id") val keyId: String,
    )

    private data class Device(
        @SerializedName("x25519_private_key") val privateKey: String,
        @SerializedName("x25519_public_key") val publicKey: String,
    )

    private data class EnvelopeCase(
        @SerializedName("ctx") val ctx: String,
        @SerializedName("payload_utf8") val payloadUtf8: String,
        @SerializedName("envelope") val envelope: Envelope,
        @SerializedName("signing_input") val signingInput: String,
    )

    private data class NegativeCase(
        @SerializedName("name") val name: String,
        @SerializedName("reason") val reason: String,
        @SerializedName("verify_ctx") val verifyCtx: String,
        @SerializedName("envelope") val envelope: Envelope,
    )

    private data class Vectors(
        @SerializedName("server") val server: Server,
        @SerializedName("device") val device: Device,
        @SerializedName("device_key") val deviceKey: String,
        @SerializedName("content_key") val contentKey: String,
        @SerializedName("wrapped_content_key") val wrappedContentKey: SealedBox,
        @SerializedName("content_plaintext_utf8") val contentPlaintext: String,
        @SerializedName("sealed_content") val sealedContent: SealedBox,
        @SerializedName("envelope") val envelope: EnvelopeCase,
        @SerializedName("negative") val negative: List<NegativeCase>,
    )

    private val vectors: Vectors by lazy {
        val stream = javaClass.classLoader?.getResourceAsStream("client-vectors.json")
        assertNotNull(
            "client-vectors.json is not on the test classpath — regenerate it with " +
                "`go run ./cmd/testvectors -out internal/cryptobox/testdata/client-vectors.json` in panel/",
            stream,
        )
        stream!!.bufferedReader().use { Gson().fromJson(it, Vectors::class.java) }
    }

    private val signPublicKey get() = Base64Url.decode(vectors.server.signPublicKey)

    // ------------------------------------------------------------ envelope --

    @Test
    fun `verifies the panel's envelope and returns the exact payload`() {
        val payload = PanelEnvelope.open(signPublicKey, vectors.envelope.ctx, vectors.envelope.envelope)
        assertEquals(vectors.envelope.payloadUtf8, String(payload, Charsets.UTF_8))
    }

    @Test
    fun `builds the same signing input the panel signed`() {
        val e = vectors.envelope.envelope
        val built = PanelEnvelope.signingInput(
            e.context,
            Base64Url.decode(e.keyId),
            e.issuedAt,
            Base64Url.decode(e.payload),
        )
        assertArrayEquals(Base64Url.decode(vectors.envelope.signingInput), built)
    }

    @Test
    fun `rejects every negative case`() {
        for (case in vectors.negative) {
            val failure = runCatching {
                PanelEnvelope.open(signPublicKey, case.verifyCtx, case.envelope)
            }.exceptionOrNull()
            assertTrue("${case.name} was accepted — ${case.reason}", failure is EnvelopeException)
        }
    }

    @Test
    fun `rejects a signature from the wrong key`() {
        val otherKey = signPublicKey.copyOf().also { it[0] = (it[0].toInt() xor 0x01).toByte() }
        assertThrows(EnvelopeException::class.java) {
            PanelEnvelope.open(otherKey, vectors.envelope.ctx, vectors.envelope.envelope)
        }
    }

    // ------------------------------------------------------------- content --

    @Test
    fun `derives the same device key as the panel`() {
        val device = DeviceKeyPair.fromPrivateKey(Base64Url.decode(vectors.device.privateKey))
        assertArrayEquals(
            "public key derived from the private key does not match the vectors",
            Base64Url.decode(vectors.device.publicKey),
            device.publicKey,
        )

        val derived = PanelCrypto.deviceKey(Base64Url.decode(vectors.server.exchPublicKey), device)
        assertArrayEquals(Base64Url.decode(vectors.deviceKey), derived)
    }

    @Test
    fun `unwraps the content key and opens the content`() {
        val device = DeviceKeyPair.fromPrivateKey(Base64Url.decode(vectors.device.privateKey))
        val deviceKey = PanelCrypto.deviceKey(Base64Url.decode(vectors.server.exchPublicKey), device)

        val contentKey = PanelCrypto.unwrapContentKey(deviceKey, vectors.wrappedContentKey)
        assertArrayEquals(Base64Url.decode(vectors.contentKey), contentKey)

        val plaintext = PanelCrypto.openContent(contentKey, vectors.sealedContent)
        assertEquals(vectors.contentPlaintext, String(plaintext, Charsets.UTF_8))
    }

    @Test
    fun `keeps the two AAD uses apart`() {
        val device = DeviceKeyPair.fromPrivateKey(Base64Url.decode(vectors.device.privateKey))
        val deviceKey = PanelCrypto.deviceKey(Base64Url.decode(vectors.server.exchPublicKey), device)
        val contentKey = PanelCrypto.unwrapContentKey(deviceKey, vectors.wrappedContentKey)

        // A wrapped key must not open as content, nor content as a wrapped key,
        // even though both are AES-GCM under a key this device holds.
        assertThrows(PanelCryptoException::class.java) {
            PanelCrypto.openContent(deviceKey, vectors.wrappedContentKey)
        }
        assertThrows(PanelCryptoException::class.java) {
            PanelCrypto.unwrapContentKey(contentKey, vectors.sealedContent)
        }
    }

    @Test
    fun `rejects a tampered ciphertext`() {
        val device = DeviceKeyPair.fromPrivateKey(Base64Url.decode(vectors.device.privateKey))
        val deviceKey = PanelCrypto.deviceKey(Base64Url.decode(vectors.server.exchPublicKey), device)
        val contentKey = PanelCrypto.unwrapContentKey(deviceKey, vectors.wrappedContentKey)

        val bytes = Base64Url.decode(vectors.sealedContent.ciphertext)
        bytes[0] = (bytes[0].toInt() xor 0x01).toByte()
        val tampered = vectors.sealedContent.copy(ciphertext = Base64Url.encode(bytes))

        assertThrows(PanelCryptoException::class.java) {
            PanelCrypto.openContent(contentKey, tampered)
        }
    }

    @Test
    fun `round-trips content it sealed itself`() {
        val contentKey = Base64Url.decode(vectors.contentKey)
        val message = "بستهٔ آزمایشی — a mixed-script payload".toByteArray(Charsets.UTF_8)

        val box = PanelCrypto.sealContent(contentKey, message)
        assertArrayEquals(message, PanelCrypto.openContent(contentKey, box))

        // A fresh nonce every time, because the key outlives any one message.
        assertTrue(PanelCrypto.sealContent(contentKey, message).nonce != box.nonce)
    }

    // ----------------------------------------------------------- base64url --

    @Test
    fun `base64url round-trips every length and rejects malformed input`() {
        for (n in 0..64) {
            val bytes = ByteArray(n) { (it * 7 + 3).toByte() }
            val encoded = Base64Url.encode(bytes)
            assertTrue("padding leaked into $encoded", !encoded.contains('='))
            assertArrayEquals("length $n", bytes, Base64Url.decode(encoded))
        }
        // Matches Go's RawURLEncoding on the values that actually travel.
        assertEquals(vectors.server.signPublicKey, Base64Url.encode(signPublicKey))

        assertThrows(IllegalArgumentException::class.java) { Base64Url.decode("AAAAA") }   // 4n+1
        assertThrows(IllegalArgumentException::class.java) { Base64Url.decode("AA=") }     // padding
        assertThrows(IllegalArgumentException::class.java) { Base64Url.decode("A+/B") }    // standard alphabet
        assertThrows(IllegalArgumentException::class.java) { Base64Url.decode("AA A") }    // whitespace
    }
}
